kind: pipeline
name: default

trigger:
  event:
    exclude: [ promote ]

steps:
- name: build
  image: jekyll/jekyll:latest
  commands:
  - touch Gemfile.lock
  - chmod a+w Gemfile.lock
  - chown -R jekyll:jekyll /drone
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec jekyll build

- name: deploy
  image: coderockr/drone-ftps
  environment:
    FTP_USERNAME:
      from_secret: username
    FTP_PASSWORD:
      from_secret: password
    PLUGIN_HOSTNAME: 62.209.128.109:21
    PLUGIN_SRC_DIR: /_site
    PLUGIN_SECURE: false
    PLUGIN_VERIFY: false
    PLUGIN_ONLY_NEWER: true
    PLUGIN_EXCLUDE: ^\.git/$
  when:
    branch:
    - master
    event:
    - push
