kind: pipeline
name: default

steps:
- name: build
  image: flortsch/ruby-native
  commands:
  - bundle install --deployment
  - bundle exec jekyll build

- name: deploy
  image: cschlosser/drone-ftps
  environment:
    FTP_USERNAME:
      from_secret: username
    FTP_PASSWORD:
      from_secret: password
    PLUGIN_HOSTNAME: 62.209.128.109:21
    PLUGIN_SRC_DIR: ./_site
    PLUGIN_SECURE: false
    PLUGIN_VERIFY: false
    PLUGIN_EXCLUDE: ^\.git/$
  when:
    branch:
    - master
    event:
    - push
