---
title: Damir Mubinov Movies
timezone: Asia/Tashkent
collections:
  clients:
    title: Clients
    output: false
  posts:
    title: Posts
    output: true
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: ''
    vimeo_link: 
    case_link: 
    case_title: 
    is_mainpage: true
- scope:
    path: ''
    type: clients
  values:
    image: 
    link: 
- scope:
    path: ''
    type: slides
  values:
    image: 
    image_mobile: 
    vimeo_link: 
- scope:
    path: ''
  values:
    layout: default
phone: "+99897 740 42 23"
meta_title: Mubinov Movies | Video Production
meta_description: Продакшн Студия  в Узбекистане. Мы делаем работающую видеорекламу
  и музыкальные клипы
meta_keywords: видео, продакшн, видео-ролик, клип, узбекистан
meta_image: "/static/img/mubinovmovies.png"
vimeo_link: https://vimeo.com/snovavideo
youtube_link: https://www.youtube.com/channel/UCVuYMzt30ZFhkJ_i0wBIrqQ
instagram_link: https://www.instagram.com/snova.video
tg_link: https://t.me/damir_mubinov
email: mubinovmovies@gmail.com
main_title: Видеопродакшн в Узбекистане
main_sub_title: Решаем бизнес-задачи с помощью видео
contact_title: Cвяжемся с вами
contact_description: оставьте свои контакты, и мы проконсультируем вас в удобной для
  вас форме
showreel_url: https://player.vimeo.com/video/382049571
works_title: НАШИ РАБОТЫ
clients_title: Наши клиенты
form_success_msg: Спасибо! Мы свяжемся с вами в ближайшее время
description: Mubinov Movies
baseurl: 
url: 
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- ".git"
- ".idea"
